-- Creación de la tabla de perfiles de usuario vinculada a Supabase Auth
create table public.profiles (
  id uuid references auth.users not null,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  primary key (id)
);

-- Tabla del Directorio de Productos de la Canasta Básica
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  unit text not null -- ej. "1 lb", "30 uds"
);

-- Tabla de Historial de Precios (Para el comparador y las gráficas)
create table public.price_history (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products not null,
  store text not null,
  price numeric not null,
  recorded_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla para el Hub de Inversiones
create table public.investment_assets (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  rate text, -- ej. "6.5% - 7.5% APY"
  category text not null, -- bank, market, commodity
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insertar Datos Semilla Locales
insert into public.products (name, category, unit) values 
('Frijol Rojo Seda', 'Granos', '1 lb'),
('Cartón de Huevos', 'Proteína', '30 uds'),
('Arroz Blanco', 'Granos', '1 lb');

insert into public.investment_assets (title, rate, description, category) values 
('Depósito a Plazo Fijo - Banco Local', '6.5% - 7.5% APY', 'Ideal para perfil conservador en El Salvador.', 'bank'),
('S&P 500 ETF (VOO)', '~10% Histórico a Largo Plazo', 'Las 500 empresas top de USA.', 'market'),
('Oro (XAU) y Plata', '+12% YTD', 'Refugio de valor mundial contra la devaluación del dólar.', 'commodity');
